<form action="index.php?route=login" method="post">
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Se connecter"/>
    </fieldset>
    <input type="hidden" name="formRegister"/>
</form>