<form method="post" action="index.php?route=create-category">
    <fieldset>
        <label for="category-name">Nom</label>
        <input type="text" name="category-name"/>
    </fieldset>
    <fieldset>
        <label for="category-description">Description</label>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Céer la catégorie"/>
    </fieldset>
    <input type="hidden" name="formCategory"/>
</form>