<section id="write">
    <form method="post" action="index.php?create-message">
        <fieldset>
            <label for="message-content">Votre message :</label>
            <textarea id="msg-content" name="message-content"
              rows="10" cols="50">
            </textarea>
        </fieldset>
        <fieldset>
            <input type="submit" name="submit" value="Envoyer"/>
        </fieldset>
        <input type="hidden" name="formMessage"/>
    </form>
</section>


