<form method="post" action="index.php?route=create-message">
    <fieldset>
        <label for="message-content">Votre message</label>
        <textarea id="msg-content" name="message-content"
          rows="3" cols="33">
            Le contenu de votre message ...
        </textarea>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Créer le salon"/>
    </fieldset>
    <input type="hidden" name="formMessage"/>
</form>