<section id="read">
    <h1 class="sr-only">Catégorie et salon</h1>
    <header>
        <ul>
            <li> Catégorie</li>
            <p>/</p>
            <li>Salon</li>
        </ul>
    </header>
    <section>
        <ul>

            <?php foreach($data['messages'] as $message){ ?>
            <li>
                <article>
                    <header>
                        <h2>De Valmont</h2>
                    </header>
                    <p>
                        <?= $message->getContent() ?>
                    </p>
                </article>
            </li>
        
        </ul>
    </section>
    <?php require "_message-form.phtml"; ?>
</section>
