<form method="post" action="index.php">
    <fieldset>
        <label for="email">Email :</label>
        <input type="text" name="email" id="email">
    </fieldset>
    <fieldset>
        <label for="username">Username :</label>
        <input type="text" name="username" id="username">
    </fieldset>
    <fieldset>
        <label for="password">password :</label>
        <input type="password" name="password" id="password">
    </fieldset>
</form>