<form method="post" action="index.php?register">
    <h2>S'inscrire</h2>
    <fieldset>
        <label for="newUsername">Username</label>
        <input type="text" name="newUsername"/>
    </fieldset>
    <fieldset>
        <label for="newEmail">Email</label>
        <input type="email" name="newEmail"/>
    </fieldset>
    <fieldset>
        <label for="newPassword">Mot de passe</label>
        <input type="password" name="newPassword"/>
    </fieldset>
    <fieldset>
        <label for="confirm-pwd">Confirmer le mot de passe</label>
        <input type="password" name="confirm-pwd"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="S'enregistrer"/>
    </fieldset>
    <input type="hidden" name="formRegister"/>
</form>